app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

logout:
    path: /logout

products:
    path: /products.json
    defaults:
        _controller: AppBundle\Controller\SerializerController:productJsonAction